// Unit tests for the pure mechanical logic in lib.mjs.
// Run: node --test plugins/rnd/scripts/batch-research/lib.test.mjs

import { test } from "node:test"
import assert from "node:assert/strict"
import {
  parseTopics,
  slug,
  isIncomplete,
  incompleteNote,
  renderReport,
  parseReportHeader,
  renderReadme,
} from "./lib.mjs"

// A trimmed but faithful fixture modeled on the real research workflow output for
// "spec driven design" (run wgfs5bg8v): full report with findings, refuted, stats.
const FULL_REPORT = {
  question: "spec driven design",
  summary: "Spec-driven development (SDD) inverts the code/spec relationship.",
  findings: [
    {
      claim: "SDD makes the specification the primary artifact.",
      confidence: "high",
      vote: "3-0",
      sources: ["https://github.com/github/spec-kit", "https://arxiv.org/html/2602.00180v1"],
      evidence: "Spec-kit: 'code serves specifications.'",
    },
    {
      claim: "Empirical quality claims are unproven.",
      confidence: "medium",
      vote: "3-0",
      sources: ["https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6515898"],
      evidence: "119 repos, ~100K PRs: no defect-reduction hypothesis supported.",
    },
  ],
  caveats: "Source mix is vendor-heavy; empirical evidence is thin.",
  openQuestions: ["Does SDD improve quality under controlled conditions?", "Can AI spec large systems?"],
  refuted: [
    { claim: "Specs are directly executable.", vote: "0-3", source: "https://github.com/github/spec-kit" },
  ],
  sources: [
    { url: "https://github.com/github/spec-kit", quality: "primary" },
    { url: "https://www.ibm.com/think/topics/spec-driven-development", quality: "secondary" },
  ],
  stats: {
    angles: 5, sourcesFetched: 20, claimsExtracted: 95, claimsVerified: 25,
    confirmed: 22, killed: 3, afterSynthesis: 11, urlDupes: 4, budgetDropped: 6,
    retriesUsed: 0, agentCalls: 102,
  },
}

// --- parseTopics ---

test("parseTopics strips list markers, comments, and blanks", () => {
  const text = [
    "- behavior driven design",
    "* test driven design",
    "1. constraint architecture",
    "",
    "# a comment",
    "  intent engineering  ",
    "   ",
    "## another comment",
  ].join("\n")
  assert.deepEqual(parseTopics(text), [
    "behavior driven design",
    "test driven design",
    "constraint architecture",
    "intent engineering",
  ])
})

test("parseTopics handles CRLF and the real topics.md shape", () => {
  const text = "- behavior driven design\r\n- spec engineering\r\n"
  assert.deepEqual(parseTopics(text), ["behavior driven design", "spec engineering"])
})

test("parseTopics only strips ONE leading marker", () => {
  assert.deepEqual(parseTopics("- - already a dash"), ["- already a dash"])
})

// --- slug ---

test("slug reproduces the existing report slugs", () => {
  assert.equal(slug("spec driven design"), "spec-driven-design")
  assert.equal(slug("Document-Driven Design"), "document-driven-design")
  assert.equal(slug("domain driven design"), "domain-driven-design")
})

test("slug collapses punctuation runs and trims edges", () => {
  assert.equal(slug("  Hello, World!!  "), "hello-world")
  assert.equal(slug("A & B / C"), "a-b-c")
})

test("slug caps at 60 chars with no trailing hyphen", () => {
  const s = slug("a".repeat(58) + " " + "b".repeat(20))
  assert.ok(s.length <= 60)
  assert.ok(!s.endsWith("-"))
})

// --- isIncomplete / incompleteNote ---

test("isIncomplete: full report is complete", () => {
  assert.equal(isIncomplete({ topic: "x", report: FULL_REPORT }), false)
})

test("isIncomplete: null report, empty findings, or error are incomplete", () => {
  assert.equal(isIncomplete({ topic: "x", report: null, error: "boom" }), true)
  assert.equal(isIncomplete({ topic: "x", report: { findings: [] } }), true)
  assert.equal(isIncomplete({ topic: "x", report: { findings: [{}], error: "synthesis failed" } }), true)
})

test("incompleteNote prefers the captured error", () => {
  assert.equal(incompleteNote({ report: null, error: "workflow threw" }), "workflow threw")
  assert.equal(incompleteNote({ report: { findings: [] } }), "no findings survived verification")
})

// --- renderReport ---

test("renderReport: full report has every section and a stats footer", () => {
  const md = renderReport({ topic: "spec driven design", report: FULL_REPORT }, "2026-06-24")
  assert.match(md, /^# spec driven design$/m)
  assert.match(md, /^> Generated by \/ae-research → research on 2026-06-24$/m)
  assert.match(md, /^## Summary$/m)
  assert.match(md, /^## Findings$/m)
  assert.match(md, /- \*\*SDD makes the specification the primary artifact\.\*\* — confidence: high/)
  assert.match(md, /Sources: https:\/\/github\.com\/github\/spec-kit, https:\/\/arxiv\.org\/html\/2602\.00180v1/)
  assert.match(md, /^## Caveats$/m)
  assert.match(md, /^## Open questions$/m)
  assert.match(md, /^## Refuted claims$/m)
  assert.match(md, /- "Specs are directly executable\." — vote 0-3 — https:\/\/github\.com\/github\/spec-kit/)
  assert.match(md, /^## Sources$/m)
  assert.match(md, /- https:\/\/github\.com\/github\/spec-kit \(primary\)/)
  assert.match(md, /^_stats: angles=5, sourcesFetched=20, .*retriesUsed=0, agentCalls=102_$/m)
  assert.doesNotMatch(md, /⚠️/) // not incomplete
})

test("renderReport: omits Refuted section when empty", () => {
  const r = { ...FULL_REPORT, refuted: [] }
  const md = renderReport({ topic: "t", report: r }, "2026-06-24")
  assert.doesNotMatch(md, /## Refuted claims/)
})

test("renderReport: incomplete (empty findings) gets a marker and placeholder", () => {
  const entry = { topic: "domain driven design", report: { ...FULL_REPORT, findings: [], summary: "partial" } }
  const md = renderReport(entry, "2026-06-24")
  assert.match(md, /^> ⚠️ \*\*Incomplete\*\* — no findings survived verification$/m)
  assert.match(md, /_No findings survived verification\._/)
})

test("renderReport: failed run (null report + error) still renders", () => {
  const entry = { topic: "boom topic", report: null, error: "workflow timed out" }
  const md = renderReport(entry, "2026-06-24")
  assert.match(md, /^# boom topic$/m)
  assert.match(md, /^> ⚠️ \*\*Incomplete\*\* — workflow timed out$/m)
  assert.match(md, /_No summary produced\._/)
  assert.match(md, /_stats: _/) // empty stats render cleanly
})

test("renderReport: collapses a multi-line error note to a single line", () => {
  // Mirrors the real e2e failure (TelemetrySafeError with a stack trace).
  const entry = {
    topic: "behavior driven design",
    report: null,
    error:
      "TelemetrySafeError: agent({schema}): StructuredOutput retry cap (5) exceeded\n    at <anonymous> (cli.js:1:1)\n    at processTicksAndRejections (native:7:39)",
  }
  const md = renderReport(entry, "2026-06-24")
  const markerLine = md.split("\n").find((l) => l.startsWith("> ⚠️"))
  assert.ok(markerLine)
  assert.doesNotMatch(markerLine, /\bat </) // no stack-trace frames leaked in
  assert.match(markerLine, /^> ⚠️ \*\*Incomplete\*\* — TelemetrySafeError: .*retry cap \(5\) exceeded$/)
  // And the header parser recovers exactly that single-line note.
  assert.equal(parseReportHeader(md).note, "TelemetrySafeError: agent({schema}): StructuredOutput retry cap (5) exceeded")
})

// --- parseReportHeader (round-trip with renderReport) ---

test("parseReportHeader round-trips renderReport output", () => {
  const md = renderReport({ topic: "spec driven design", report: FULL_REPORT }, "2026-06-24")
  const h = parseReportHeader(md)
  assert.equal(h.topic, "spec driven design")
  assert.equal(h.date, "2026-06-24")
  assert.equal(h.incomplete, false)
})

test("parseReportHeader extracts the incomplete note", () => {
  const entry = { topic: "domain driven design", report: null, error: "synthesis failed" }
  const md = renderReport(entry, "2026-06-24")
  const h = parseReportHeader(md)
  assert.equal(h.topic, "domain driven design")
  assert.equal(h.incomplete, true)
  assert.equal(h.note, "synthesis failed")
})

// --- renderReadme ---

test("renderReadme sorts by slug and marks incomplete entries", () => {
  const md = renderReadme([
    { topic: "spec driven design", slug: "spec-driven-design", date: "2026-06-24", incomplete: false, note: "" },
    { topic: "domain driven design", slug: "domain-driven-design", date: "2026-06-24", incomplete: true, note: "synthesis failed" },
  ])
  assert.match(md, /^# Research Reports$/m)
  // domain- sorts before spec-
  const lines = md.split("\n").filter((l) => l.startsWith("- ["))
  assert.equal(lines[0], "- [domain driven design](domain-driven-design.md) — 2026-06-24 _(incomplete — synthesis failed)_")
  assert.equal(lines[1], "- [spec driven design](spec-driven-design.md) — 2026-06-24")
})
