// Pure, deterministic mechanical logic for /ae-research.
// No filesystem or process access here — everything is a pure function so it is
// fully unit-testable (see lib.test.mjs). The CLI wrapper (cli.mjs) is the only
// place that touches disk.

// Parse a topics file's text into a clean topic list. Ports the command's
// original sed/grep rules:
//   sed -E 's/^[[:space:]]*([-*]|[0-9]+\.)[[:space:]]+//; s/^[[:space:]]+//; s/[[:space:]]+$//'
//   | grep -vE '^[[:space:]]*(#|$)'
// i.e. strip one leading list marker (`- `, `* `, `N. `), trim, then drop blank
// lines and `#` comments.
export function parseTopics(text) {
  return String(text)
    .split(/\r?\n/)
    .map((line) =>
      line
        .replace(/^\s*([-*]|\d+\.)\s+/, "") // strip one leading list marker
        .replace(/^\s+/, "")
        .replace(/\s+$/, "")
    )
    .filter((s) => s !== "" && !s.startsWith("#"))
}

// Slug a topic. Ports: tr '[:upper:]' '[:lower:]'
//   | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' | cut -c1-60
// (with a final trim so a 60-char truncation can't leave a trailing '-').
export function slug(topic) {
  return String(topic)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+/, "")
    .replace(/-+$/, "")
    .slice(0, 60)
    .replace(/-+$/, "")
}

// An entry is { topic, slug, report, error } where `report` is the object
// the research workflow returned (or null if the run threw) and `error` is a captured
// error string (or null/undefined).
export function isIncomplete(entry) {
  const r = entry.report
  const findings = r && Array.isArray(r.findings) ? r.findings : []
  return !r || findings.length === 0 || !!(entry.error || (r && r.error))
}

export function incompleteNote(entry) {
  const r = entry.report || {}
  return entry.error || r.error || "no findings survived verification"
}

// Render a compact `key=value, key=value` stats footer from a stats object,
// preserving insertion order. Returns "" if there are no stats.
function renderStats(stats) {
  if (!stats || typeof stats !== "object") return ""
  return Object.entries(stats)
    .map(([k, v]) => `${k}=${v}`)
    .join(", ")
}

// Render one report's Markdown. `entry.topic` is the title; `date` is the
// generation date (YYYY-MM-DD). Mirrors the template the command used, including
// the incomplete-report rules.
export function renderReport(entry, date) {
  const r = entry.report || {}
  const findings = Array.isArray(r.findings) ? r.findings : []
  const openQuestions = Array.isArray(r.openQuestions) ? r.openQuestions : []
  const refuted = Array.isArray(r.refuted) ? r.refuted : []
  const sources = Array.isArray(r.sources) ? r.sources : []
  const incomplete = isIncomplete(entry)

  const out = []
  out.push(`# ${entry.topic}`)
  out.push("")
  out.push(`> Generated by /ae-research → research on ${date}`)
  out.push("")
  if (incomplete) {
    // Collapse the note to a single line (errors can carry multi-line stack traces).
    const note = incompleteNote(entry).split("\n")[0].replace(/\s+/g, " ").trim()
    out.push(`> ⚠️ **Incomplete** — ${note}`)
    out.push("")
  }

  out.push("## Summary")
  out.push(r.summary || "_No summary produced._")
  out.push("")

  out.push("## Findings")
  if (findings.length === 0) {
    out.push("_No findings survived verification._")
  } else {
    for (const f of findings) {
      const fsrc = Array.isArray(f.sources) ? f.sources.join(", ") : ""
      out.push(`- **${f.claim}** — confidence: ${f.confidence}`)
      out.push(`  - Evidence: ${f.evidence}`)
      out.push(`  - Sources: ${fsrc}`)
    }
  }
  out.push("")

  out.push("## Caveats")
  out.push(r.caveats || "_None._")
  out.push("")

  out.push("## Open questions")
  if (openQuestions.length === 0) {
    out.push("_None._")
  } else {
    for (const q of openQuestions) out.push(`- ${q}`)
  }
  out.push("")

  // Omit the Refuted section entirely when empty.
  if (refuted.length > 0) {
    out.push("## Refuted claims")
    for (const c of refuted) out.push(`- "${c.claim}" — vote ${c.vote} — ${c.source}`)
    out.push("")
  }

  out.push("## Sources")
  if (sources.length === 0) {
    out.push("_None._")
  } else {
    for (const s of sources) out.push(`- ${s.url} (${s.quality})`)
  }
  out.push("")

  out.push("---")
  out.push(`_stats: ${renderStats(r.stats)}_`)
  out.push("")
  return out.join("\n")
}

// Extract the index-relevant header fields from a rendered report's Markdown,
// so the README can be regenerated deterministically from the files on disk
// (including reports from earlier runs).
export function parseReportHeader(markdown) {
  const text = String(markdown)
  const topicMatch = text.match(/^#\s+(.+)$/m)
  const dateMatch = text.match(/^>\s+Generated by .* on (\d{4}-\d{2}-\d{2})/m)
  const incompleteMatch = text.match(/^>\s+⚠️\s+\*\*Incomplete\*\*\s+—\s+(.+)$/m)
  return {
    topic: topicMatch ? topicMatch[1].trim() : "",
    date: dateMatch ? dateMatch[1] : "",
    incomplete: !!incompleteMatch,
    note: incompleteMatch ? incompleteMatch[1].trim() : "",
  }
}

// Render the research/README.md index. `entries` is an array of
// { topic, slug, date, incomplete, note }. Output is deterministic (sorted by slug).
export function renderReadme(entries) {
  const sorted = [...entries].sort((a, b) => a.slug.localeCompare(b.slug))
  const out = []
  out.push("# Research Reports")
  out.push("")
  out.push("Cited Markdown reports generated by `/ae-research` → `research`.")
  out.push("")
  for (const e of sorted) {
    const marker = e.incomplete ? ` _(incomplete — ${e.note})_` : ""
    const date = e.date ? ` — ${e.date}` : ""
    out.push(`- [${e.topic}](${e.slug}.md)${date}${marker}`)
  }
  out.push("")
  return out.join("\n")
}
